
jwt:
  secret: selectData
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

logging:
  file: logs/selectdata.log
  level:
      root: info
server:
  port: 80
spring:
  profiles:
      active: dev,swagger,actuator


